#include <csignal>
#include <future>
#include <iostream>
#include <memory>
#include <atomic>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
#ifdef _WIN32
#include <windows.h>
#endif

#include "include/agent.h"
#include "include/resource_manager.h"
#include "include/session_manager.h"
#include "include/config/agent_config_json.h"
#include "include/config/agent_config_store.h"
#include "include/config/config_watcher.h"
#include "examples/jiuwenClaw/adapters/http_server/http_server.h"
#include "examples/jiuwenClaw/adapters/feishu/feishu_bot.h"
#include "examples/jiuwenClaw/channels/channel_manager.h"
#include "examples/jiuwenClaw/channels/channel_service.h"
#include "examples/jiuwenClaw/mcp/mcp_server_manager.h"
// Heartbeat management & Cron watcher module
#include "examples/jiuwenClaw/cron_watcher.h"
#include "examples/jiuwenClaw/heartbeat_manager.h"
#include "examples/jiuwenClaw/reserved_sessions.h"
// Demo-specific tools
#include "examples/jiuwenClaw/tools/cron_tool.h"
#include "examples/jiuwenClaw/tools/notebook_edit_tool.h"
#include "examples/jiuwenClaw/tools/notify_tool.h"

#include "examples/jiuwenClaw/utils/encoding.h"
#include "examples/jiuwenClaw/utils/logger.h"
#include "examples/jiuwenClaw/utils/string_utils.h"

#include "third_party/include/nlohmann/json.hpp"

using namespace jiuwen;
using namespace jiuwenClaw;

std::atomic<bool> g_Running{true};
std::unique_ptr<HttpServer> g_HttpServer;
std::unique_ptr<ConfigWatcher> g_ConfigWatcher;

// Forward declarations for hot-reload helpers (defined below).
bool ReloadAgent(const std::string& agentId);
void ReloadChannels();
void ReloadAll();

void SignalHandler(int signum)
{
    if (signum == SIGINT || signum == SIGTERM) {
        g_Running = false;
    }
}

AgentConfig BuildAgentConfig()
{
    AgentConfig config;
    config.id = "demo-agent";
    config.name = "Demo Agent";
    config.mode = AgentWorkMode::REACT;
    config.maxIterations = 100;

    // Data directory layout
    config.dataBasePath = "./data";

    // Context configuration (session-agnostic, per-session paths are generated by SessionManager)
    config.contextConfig.sessionId = kDefaultSessionId;
    config.contextConfig.storageType = ContextConfig::StorageType::JSON_FILE;
    config.contextConfig.storagePath = ""; // SessionManager will set this per-session

    // Memory configuration: idle poll interval + system sessions excluded
    // from consolidation. Cron / heartbeat events are still persisted for
    // audit but never consolidated into long-term memory, so the memory
    // reflects real user conversations rather than mechanical ticks.
    config.memoryConfig.idleConsolidationSeconds = 60;
    config.memoryConfig.excludedConsolidationSessionIds = {kHeartbeatSessionId, kCronSessionId};

    config.skillDirectory = "./my_skills";

    config.modelConfig.baseUrl = "<YOUR_MODEL_BASE_URL>";
    config.modelConfig.apiKey = "<YOUR_MODEL_API_KEY>";
    config.modelConfig.modelName = "<YOUR_MODEL_NAME>";
    config.modelConfig.formatType = ModelFormatType::OPENAI;

    config.modelConfig.extraParams.Set("max_tokens", 4096);
    config.modelConfig.extraParams.Set("temperature", 0.0f);
    config.modelConfig.extraParams.Set("top_p", 0.0f);
    config.modelConfig.extraParams.Set("tool_choice", std::string("auto"));

    config.promptTemplates["react_system"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/REACT_SYSTEM.md"
    };

    config.promptTemplates["agents"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/AGENTS.md"
    };
    config.promptTemplates["soul"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/SOUL.md"
    };
    config.promptTemplates["user"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/USER.md"
    };
    config.promptTemplates["tools_md"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/TOOLS.md"
    };

    // Default tools for all sessions
    auto& rm = ResourceManager::GetInstance();
    auto allTools = rm.GetAvailableTools();
    config.defaultTools = allTools;

    return config;
}

void RegisterDemoTools()
{
    auto& rm = ResourceManager::GetInstance();
    rm.RegisterTool("notebook_edit", []() { return std::make_unique<NotebookEditTool>(); });
    rm.RegisterTool("cron", []() { return std::make_unique<CronTool>(); });
    rm.RegisterTool("notify", []() { return std::make_unique<NotifyTool>(); });
}

void RunCliMode()
{
    std::cout << "\nEnter '/exit' to quit, '/session <id>' to switch session.\n" << std::flush;

    // Session management for CLI
    std::string currentSession = kDefaultSessionId;

    std::string query;
    while (g_Running) {
        std::cout << "[" << currentSession << "]> " << std::flush;
        if (!std::getline(std::cin, query)) {
            break;
        }

        if (query == "/exit") {
            LOG(INFO) << "User input: " << query;
            g_Running = false;
            break;
        }

        if (query.empty()) {
            continue;
        }

        // Handle /session command to switch between sessions
        if (query.substr(0, 9) == "/session ") {
            currentSession = TrimStr(query.substr(9));
            if (currentSession.empty()) {
                currentSession = kDefaultSessionId;
            }
            // Create session via SessionManager
            GetSessionManager().GetOrCreateSession(currentSession);
            LOG(INFO) << "[CLI] Switched to session: " << currentSession;
            std::cout << "[Info] Switched to session: " << currentSession << "\n";
            continue;
        }

        // Handle /sessions command to list active sessions
        if (query == "/sessions") {
            auto ids = GetSessionManager().GetSessionIds();
            std::cout << "Active sessions (" << ids.size() << "): ";
            for (size_t i = 0; i < ids.size(); ++i) {
                if (i > 0) {
                    std::cout << ", ";
                }
                std::cout << ids[i] << (ids[i] == currentSession ? " (current)" : "");
            }
            std::cout << "\n";
            continue;
        }

        // Handle /reload [agent [<id>] | channels]
        if (query == "/reload" || query.substr(0, 8) == "/reload ") {
            std::string rest = query.length() > 8 ? TrimStr(query.substr(8)) : "";
            if (rest.empty()) {
                std::cout << "[Reload] Reloading agents.json and channels.json...\n";
                ReloadAll();
                std::cout << "[Reload] Done.\n";
            } else if (rest == "channels") {
                std::cout << "[Reload] Reconciling channels...\n";
                ReloadChannels();
                std::cout << "[Reload] Done.\n";
            } else if (rest.substr(0, 5) == "agent") {
                std::string id = rest.length() > 6 ? TrimStr(rest.substr(6)) : "";
                std::cout << "[Reload] Reloading agent '" << (id.empty() ? "<default>" : id) << "'...\n";
                bool ok = ReloadAgent(id);
                std::cout << (ok ? "[Reload] Done.\n" : "[Reload] Failed (see logs).\n");
            } else {
                std::cout << "Usage: /reload | /reload agent [<id>] | /reload channels\n";
            }
            continue;
        }

        // Handle /config show [<id>]
        if (query == "/config show" || query.substr(0, 13) == "/config show ") {
            std::string id = query.length() > 13 ? TrimStr(query.substr(13)) : "";
            if (id.empty()) {
                id = GetSessionManager().GetConfig().id;
            }
            auto cfgOpt = AgentConfigStore::Instance().Get(id);
            if (!cfgOpt) {
                std::cout << "[Config] No agent with id=" << id << "\n";
            } else {
                std::cout << AgentConfigToJson(*cfgOpt).dump(2) << "\n";
            }
            continue;
        }

        std::string utf8Query = LocalToUTF8(query);
        utf8Query = CleanInput(utf8Query);
        utf8Query = FixUTF8(utf8Query);
        utf8Query = TrimStr(utf8Query);
        if (utf8Query.empty()) {
            continue;
        }

        std::cout << "Processing...\n";

        std::string utf8Carry;
        bool gotStreamText = false;

        const std::string TAG_STREAM = "[STREAM]";
        const std::string TAG_STATUS = "[STATUS]";
        const std::string TAG_TOOL_CALLS = "[TOOL_CALLS]";
        const std::string TAG_TOOL_RESPONSE = "[TOOL_RESPONSE";  // closing ']' may include call id
        const std::string TAG_FINAL = "[FINAL]";
        const std::string TAG_ASK_USER = "[ASK_USER]";
        const std::string TAG_ASK_USER_END = "[/ASK_USER]";

        // Invoke via SessionManager with per-session lock and concurrency gate
        SessionInvokeResult result = GetSessionManager().Invoke(
            currentSession,
            utf8Query,
            [&](const std::string& resp) {
                if (resp.empty()) {
                    return;
                }

                std::string s = resp;
                // 0. Ask-user prompt: spawn a detached helper that reads
                // stdin and calls Agent::ProvideUserResponse so the worker
                // thread (currently blocked in AskUserTool::Invoke) can wake
                // up. The callback itself must return immediately, otherwise
                // streaming would be stalled.
                if (s.find(TAG_ASK_USER) != std::string::npos) {
                    size_t start = s.find(TAG_ASK_USER);
                    size_t end = s.find(TAG_ASK_USER_END, start);
                    if (end != std::string::npos) {
                        std::string payload = s.substr(start + TAG_ASK_USER.length(),
                                                       end - start - TAG_ASK_USER.length());
                        try {
                            auto j = nlohmann::json::parse(payload);
                            std::string requestId = j.value("request_id", std::string{});
                            std::string question = j.value("question", std::string{});
                            bool multiple = j.value("multiple", false);
                            std::vector<std::string> options;
                            if (j.contains("options") && j["options"].is_array()) {
                                for (const auto& v : j["options"]) {
                                    if (v.is_string()) {
                                        options.push_back(v.get<std::string>());
                                    }
                                }
                            }
                            if (!requestId.empty()) {
                                std::thread([requestId, question, options, multiple]() {
                                    std::cout << "\n\n[Agent 询问] " << question << "\n";
                                    if (!options.empty()) {
                                        for (size_t i = 0; i < options.size(); ++i) {
                                            std::cout << "  [" << (i + 1) << "] " << options[i] << "\n";
                                        }
                                        std::cout << (multiple ? "请输入编号（多选用逗号分隔，留空跳过，60s 超时）: "
                                                                : "请输入编号（留空跳过，60s 超时）: ");
                                    } else {
                                        std::cout << "请输入答复（留空跳过，60s 超时）: ";
                                    }
                                    std::cout.flush();
                                    std::string line;
                                    if (!std::getline(std::cin, line)) {
                                        line.clear();
                                    }
                                    std::string answer;
                                    if (!options.empty() && !line.empty()) {
                                        // Map 1-based indexes to option labels
                                        std::vector<std::string> picks;
                                        std::stringstream ss(line);
                                        std::string item;
                                        while (std::getline(ss, item, ',')) {
                                            try {
                                                int idx = std::stoi(TrimStr(item));
                                                if (idx >= 1 && static_cast<size_t>(idx) <= options.size()) {
                                                    picks.push_back(options[idx - 1]);
                                                }
                                            } catch (...) {
                                                // Treat as free text if it is not a number
                                                picks.push_back(TrimStr(item));
                                            }
                                            if (!multiple && !picks.empty()) {
                                                break;
                                            }
                                        }
                                        nlohmann::json ans;
                                        ans["answers"] = picks;
                                        answer = ans.dump();
                                    } else {
                                        nlohmann::json ans;
                                        ans["text"] = line;
                                        answer = ans.dump();
                                    }
                                    if (auto agent = GetSessionManager().GetAgent()) {
                                        GetSessionManager().ProvideUserResponse(requestId, answer);
                                    }
                                }).detach();
                            }
                        } catch (const std::exception& e) {
                            LOG(WARN) << "[CLI] Failed to parse ASK_USER payload: " << e.what();
                        }
                    }
                    return;
                }

                // 1. Tool calls, content overlaps with streaming, print call metadata
                if (s.find(TAG_TOOL_CALLS) != std::string::npos) {
                    size_t start_pos = s.find(TAG_TOOL_CALLS);
                    start_pos += TAG_TOOL_CALLS.length();
                    while (start_pos < s.length() && (s[start_pos] == ' ' || s[start_pos] == '\n')) {
                        ++start_pos;
                    }
                    std::string payload = TrimStr(s.substr(start_pos));
                    try {
                        auto j = nlohmann::json::parse(payload);
                        std::string callId = j.value("id", std::string{});
                        std::string name = j.value("name", std::string{"tool"});
                        std::string argsText;
                        if (j.contains("arguments")) {
                            if (j["arguments"].is_string()) {
                                argsText = j["arguments"].get<std::string>();
                            } else {
                                argsText = j["arguments"].dump(2);
                            }
                        }
                        std::cout << "\n\n**Tool Call**:\n";
                        if (!callId.empty()) {
                            std::cout << "ID: " << UTF8ToLocal(callId) << "\n";
                        }
                        std::cout << "Name: " << UTF8ToLocal(name) << "\n";
                        if (!argsText.empty()) {
                            std::cout << "Arguments:\n" << UTF8ToLocal(argsText) << "\n";
                        }
                    } catch (const std::exception&) {
                        std::cout << "\n\n**Tool Call**:\n" << UTF8ToLocal(payload) << "\n";
                    }
                    return;
                }

                // 2. Tool response (supports [TOOL_RESPONSE] and [TOOL_RESPONSE <call_id>])
                if (s.find(TAG_TOOL_RESPONSE) != std::string::npos) {
                    size_t start_pos = s.find(TAG_TOOL_RESPONSE);
                    if (start_pos != std::string::npos) {
                        size_t close = s.find(']', start_pos);
                        if (close != std::string::npos) {
                            start_pos = close + 1;
                            while (start_pos < s.length() && s[start_pos] == ' ') {
                                ++start_pos;
                            }
                            std::string toolRespText = s.substr(start_pos);
                            std::cout << "\n\n**Tool Response**: \n" << UTF8ToLocal(toolRespText) << std::endl;
                        }
                    }
                    return;
                }

                // 3. Streaming output
                if (s.find(TAG_STREAM) != std::string::npos) {
                    size_t start_pos = s.find(TAG_STREAM);
                    if (start_pos != std::string::npos) {
                        start_pos += TAG_STREAM.length();
                        std::string cleanText = s.substr(start_pos);

                        if (!cleanText.empty()) {
                            gotStreamText = true;
                            std::string fixed = FixUTF8Streaming(cleanText, utf8Carry);
                            std::cout << UTF8ToLocal(fixed) << std::flush;
                        }
                    }
                    return;
                }

                // 4. Status info
                if (s.find(TAG_STATUS) != std::string::npos) {
                    size_t start_pos = s.find(TAG_STATUS);
                    if (start_pos != std::string::npos) {
                        start_pos += TAG_STATUS.length();
                        while (start_pos < s.length() && s[start_pos] == ' ') {
                            ++start_pos;
                        }
                        std::string statusText = s.substr(start_pos);
                        std::string formattedStatus = "\n>> " + TrimStr(statusText) + "\n";
                        std::cout << UTF8ToLocal(formattedStatus) << std::flush;
                    }
                    return;
                }

                // 5. [FINAL] carries the final answer. When the model already
                // streamed its tokens they were printed above; otherwise (e.g.
                // a retry path where streaming was suppressed) display the
                // carried text here so the answer is never lost.
                if (s.find(TAG_FINAL) != std::string::npos) {
                    if (!gotStreamText) {
                        size_t pos = s.find(TAG_FINAL);
                        if (pos != std::string::npos) {
                            pos += TAG_FINAL.length();
                            while (pos < s.length() && s[pos] == ' ') ++pos;
                            std::string finalText = s.substr(pos);
                            while (!finalText.empty() && (finalText.back() == '\n' || finalText.back() == '\r')) {
                                finalText.pop_back();
                            }
                            if (!finalText.empty()) {
                                std::cout << UTF8ToLocal(finalText) << std::flush;
                            }
                        }
                    }
                    return;
                }

                // 6. Fallback: plain text without tag
                if (!s.empty()) {
                    std::cout << UTF8ToLocal(s) << std::flush;
                }
            }
        );

        std::cout << "\n";
    }
}

// === Hot-reload helpers ===

// Reload one agent by id (default = current SessionManager config id).
// Returns true on success, false on error (e.g. id not found).
bool ReloadAgent(const std::string& agentId)
{
    auto& store = AgentConfigStore::Instance();
    store.Load(); // Re-read agents.json (merged with defaults)

    std::string id = agentId;
    if (id.empty()) {
        id = GetSessionManager().GetConfig().id;
        if (id.empty()) {
            id = "demo-agent";
        }
    }

    auto cfgOpt = store.Get(id);
    if (!cfgOpt) {
        LOG(ERR) << "[Reload] No agent found with id=" << id;
        return false;
    }

    std::string err;
    if (GetSessionManager().ReloadAgent(*cfgOpt, &err)) {
        LOG(INFO) << "[Reload] Agent '" << id << "' hot-reloaded successfully";
        return true;
    }
    LOG(ERR) << "[Reload] Hot-reload failed for '" << id << "': " << err;
    return false;
}

void ReloadChannels()
{
    auto& mgr = ChannelManager::GetInstance();
    mgr.Load(); // re-read channels.json
    ChannelService::Instance().ReconcileAll();
    LOG(INFO) << "[Reload] Channels reconciled";
}

void ReloadAll()
{
    ReloadAgent("");
    ReloadChannels();
}

void PrintUsage()
{
    std::cout << "Usage: jiuwenClaw [OPTIONS]\n"
              << "\n"
              << "Options:\n"
              << "  --server       Enable all integrations (HTTP REST API + configured channels)\n"
              << "  --port <N>     Set server port (default: 8080)\n"
              << "  --host <IP>    Set server host (default: 127.0.0.1)\n"
              << "  --no-cli       Disable CLI mode (run only as daemon)\n"
              << "  --watch-config Auto-reload agent/channels when files change (polled)\n"
              << "  --help         Show this help message\n"
              << "\n"
              << "Notes:\n"
              << "  Agent overrides are loaded from ./data/agents.json (multi-agent ready);\n"
              << "  if absent, the in-code BuildAgentConfig() default is used.\n"
              << "  Channels (e.g. Feishu) are loaded from ./data/channels.json.\n"
              << "  Use the web UI, the REST API, or edit the files directly.\n"
              << "\n"
              << "Interactive CLI commands (in default mode):\n"
              << "  /exit                  Quit\n"
              << "  /session <id>          Switch to a different session\n"
              << "  /sessions              List active sessions\n"
              << "  /reload                Reload agents.json + channels.json\n"
              << "  /reload agent [<id>]   Reload one agent (default: demo-agent)\n"
              << "  /reload channels       Reconcile channels with channels.json\n"
              << "  /config show [<id>]    Print the effective agent config\n"
              << "\n"
              << "Examples:\n"
              << "  jiuwenClaw                          # CLI only (default)\n"
              << "  jiuwenClaw --server                 # CLI + HTTP server + all configured channels\n"
              << "  jiuwenClaw --server --no-cli        # Daemon mode (HTTP + channels)\n"
              << "  jiuwenClaw --server --watch-config  # Server with auto-reload on file change\n"
              << std::endl;
}

int main(int argc, char* argv[])
{
    std::cout << "jiuwenClaw - Agent powered by jiuwen-lite Agent Framework\n====================\n" << std::flush;

    bool enableServer = false;
    bool enableCli = true;
    bool enableWatch = false;
    std::string serverHost = "127.0.0.1";
    int serverPort = 8080;

    // Parse command line arguments
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--server") {
            enableServer = true;
        } else if (arg == "--no-cli") {
            enableCli = false;
        } else if (arg == "--watch-config") {
            enableWatch = true;
        } else if (arg == "--port" && i + 1 < argc) {
            serverPort = std::stoi(argv[++i]);
        } else if (arg == "--host" && i + 1 < argc) {
            serverHost = argv[++i];
        } else if (arg == "--help") {
            PrintUsage();
            return 0;
        }
    }

    // Register additional tools
    RegisterDemoTools();
    std::cout << "[Boot] Demo tools registered\n" << std::flush;

    // Build the hard-coded default (kept for backward compatibility)
    AgentConfig defaultConfig = BuildAgentConfig();
    std::cout << "[Boot] Default AgentConfig built (id=" << defaultConfig.id << ")\n" << std::flush;

    // Register the default in the config store, then load + merge agents.json.
    auto& cfgStore = AgentConfigStore::Instance();
    cfgStore.SetPersistPath("./data/agents.json");
    cfgStore.RegisterDefault(defaultConfig);
    auto effective = cfgStore.Load();

    // Use the merged config for the primary agent id.
    AgentConfig config = defaultConfig;
    auto it = effective.find(defaultConfig.id);
    if (it != effective.end()) {
        config = it->second;
        std::cout << "[Boot] Effective AgentConfig (default + agents.json overrides) ready\n"
                  << std::flush;
    } else {
        std::cout << "[Boot] No override in agents.json; using code default\n" << std::flush;
    }

    InitSessionManager(config);
    std::cout << "[Boot] SessionManager initialized\n" << std::flush;

    // Register application-layer reserved sessions with the core library so
    // they cannot be deleted via /api/sessions DELETE. The core library
    // already auto-registers __DEFAULT__ (its own MakeSessionKey fallback);
    // jiuwenClaw additionally protects __HEARTBEAT__ and __CRON__ here. The
    // same ids are listed in MemoryConfig::excludedConsolidationSessionIds
    // (set in BuildAgentConfig) so memory consolidation skips their events.
    GetSessionManager().RegisterReservedSession(kHeartbeatSessionId);
    GetSessionManager().RegisterReservedSession(kCronSessionId);
    std::cout << "[Boot] Reserved sessions registered (__HEARTBEAT__, __CRON__)\n" << std::flush;

    // Load MCP servers from the application-layer registry (mcp_servers.json).
    // The framework itself only knows how to register/connect McpServerConfig
    // objects; it does not care where those configs come from. Other apps
    // can supply them via hard-coded values or their own config loader.
    {
        auto& mcpMgr = McpServerManager::GetInstance();
        mcpMgr.SetPersistPath("./data/mcp_servers.json");
        mcpMgr.Load(); // tolerate missing file (empty pool is a valid state)
        auto configs = mcpMgr.ToFrameworkConfigs();
        if (!configs.empty()) {
            ResourceManager::GetInstance().LoadMCPServers(configs);
            // Sync MCP-discovered tools into the Agent so they appear in the prompt
            if (auto agent = GetSessionManager().GetAgent()) {
                int n = agent->SyncMcpTools();
                std::cout << "[Boot] Synced " << n << " MCP tool(s) to Agent\n" << std::flush;
            }
            std::cout << "[Boot] Loaded " << configs.size()
                      << " MCP server(s) from mcp_servers.json\n" << std::flush;
        } else {
            std::cout << "[Boot] No MCP servers configured (edit ./data/mcp_servers.json or use the web UI to add)\n"
                      << std::flush;
        }
    }

    // Initialize heartbeat and cron using reserved sessions.
    // Held in unique_ptr so they can be stopped (and their threads joined)
    // deterministically in the shutdown section, before SessionManager is
    // drained, rather than at end-of-main stack unwinding.
    auto heartbeat = std::make_unique<HeartbeatManager>(
        "./data/HEARTBEAT.md",
        config.modelConfig,
        300
    );
    std::cout << "[Boot] HeartbeatManager constructed\n" << std::flush;

    auto cronWatcher = std::make_unique<CronWatcher>("./data", config.modelConfig, 60);
    std::cout << "[Boot] CronWatcher constructed\n" << std::flush;

    // Start HTTP server if enabled
    if (enableServer) {
        g_HttpServer = std::make_unique<HttpServer>();
        HttpServerConfig httpConfig;
        httpConfig.host = serverHost;
        httpConfig.port = serverPort;
        httpConfig.staticDir = "./examples/jiuwenClaw/web";
        g_HttpServer->Start(httpConfig);
        std::cout << "[Boot] HTTP server started at " << serverHost << ":" << serverPort << "\n" << std::flush;

        // Load channels from disk and start each enabled channel via ChannelService
        auto& channelMgr = ChannelManager::GetInstance();
        channelMgr.SetPersistPath("./data/channels.json");
        channelMgr.Load();
        ChannelService::Instance().StartAll();
        auto active = ChannelService::Instance().ActiveIds();
        if (active.empty()) {
            std::cout << "[Boot] No channels active (edit ./data/channels.json or use the web UI to add)\n"
                      << std::flush;
        } else {
            std::cout << "[Boot] Active channels: " << active.size() << "\n" << std::flush;
        }
    }

    // Optional config-file watcher: auto-reload on disk change
    if (enableWatch) {
        g_ConfigWatcher = std::make_unique<ConfigWatcher>();
        g_ConfigWatcher->Watch("./data/agents.json", [](const std::string& p) {
            (void)p;
            LOG(INFO) << "[Watch] agents.json changed -> hot-reload";
            ReloadAgent("");
        });
        g_ConfigWatcher->Watch("./data/channels.json", [](const std::string& p) {
            (void)p;
            LOG(INFO) << "[Watch] channels.json changed -> reconcile";
            ReloadChannels();
        });
        g_ConfigWatcher->Watch("./data/mcp_servers.json", [](const std::string& p) {
            (void)p;
            LOG(INFO) << "[Watch] mcp_servers.json changed -> reload MCP pool";
            auto& mcpMgr = McpServerManager::GetInstance();
            mcpMgr.Load();
            ResourceManager::GetInstance().LoadMCPServers(mcpMgr.ToFrameworkConfigs());
            // Sync discovered tools to live Agent
            if (auto agent = GetSessionManager().GetAgent()) {
                agent->SyncMcpTools();
            }
        });
        g_ConfigWatcher->Start(3);
        std::cout << "[Boot] Config watcher enabled (poll every 3s)\n" << std::flush;
    }

    std::signal(SIGINT, SignalHandler);
    std::signal(SIGTERM, SignalHandler);

    if (enableCli) {
        RunCliMode();
    } else {
        // Daemon mode: wait for signal
        std::cout << "[Boot] Running in daemon mode. Press Ctrl+C to stop...\n" << std::flush;
        while (g_Running) {
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
    }

    // Cleanup
    std::cout << "\n[Shutdown] Stopping services...\n" << std::flush;

    if (g_ConfigWatcher) {
        g_ConfigWatcher->Stop();
        g_ConfigWatcher.reset();
    }

    ChannelService::Instance().StopAll();

    if (g_HttpServer) {
        g_HttpServer->Stop();
        g_HttpServer.reset();
    }

    // Stop the background schedulers BEFORE draining the SessionManager so that
    // no thread can call into it afterwards. Each reset() joins its worker
    // thread (waiting for any in-flight Invoke to finish).
    cronWatcher.reset();
    heartbeat.reset();

    // Gracefully stop the Agent's consolidation thread. The singleton itself is
    // never deleted (its memory is reclaimed at process exit); this only drains
    // background work so it is joined deterministically here.
    GetSessionManager().Shutdown();

    std::cout << "[Shutdown] Goodbye.\n" << std::flush;

    return 0;
}
