#include <csignal>
#include <iostream>
#include <memory>
#include <atomic>
#include <string>
#include <vector>
#ifdef _WIN32
#include <windows.h>
#endif

#include "include/agent.h"
#include "include/resource_manager.h"
#include "include/session_manager.h"
#include "include/config/agent_config_json.h"
#include "include/config/agent_config_store.h"
#include "include/config/config_watcher.h"
#include "examples/jiuwenClaw/adapters/http_server/http_server.h"
#include "examples/jiuwenClaw/adapters/feishu/feishu_bot.h"
#include "examples/jiuwenClaw/channels/channel_manager.h"
#include "examples/jiuwenClaw/channels/channel_service.h"
#include "examples/jiuwenClaw/mcp/mcp_server_manager.h"
// Heartbeat management & Cron watcher module
#include "examples/jiuwenClaw/cron_watcher.h"
#include "examples/jiuwenClaw/heartbeat_manager.h"
// Demo-specific tools
#include "examples/jiuwenClaw/models/ark_code_model.h"
#include "examples/jiuwenClaw/tools/cron_tool.h"
#include "examples/jiuwenClaw/tools/notebook_edit_tool.h"
#include "examples/jiuwenClaw/tools/notify_tool.h"

#include "examples/jiuwenClaw/utils/encoding.h"
#include "examples/jiuwenClaw/utils/logger.h"
#include "examples/jiuwenClaw/utils/string_utils.h"

#include "third_party/include/nlohmann/json.hpp"

using namespace jiuwen;
using namespace jiuwenClaw;

std::atomic<bool> g_Running{true};
std::unique_ptr<HttpServer> g_HttpServer;
std::unique_ptr<ConfigWatcher> g_ConfigWatcher;

// Forward declarations for hot-reload helpers (defined below).
bool ReloadAgent(const std::string& agentId);
void ReloadChannels();
void ReloadAll();

void SignalHandler(int signum)
{
    if (signum == SIGINT || signum == SIGTERM) {
        g_Running = false;
    }
}

AgentConfig BuildAgentConfig()
{
    AgentConfig config;
    config.id = "demo-agent";
    config.name = "Demo Agent";
    config.mode = AgentWorkMode::REACT;
    config.maxIterations = 100;

    // Data directory layout
    config.dataBasePath = "./data";

    // Context configuration (session-agnostic, per-session paths are generated by SessionManager)
    config.contextConfig.sessionId = kDefaultSessionId;
    config.contextConfig.storageType = ContextConfig::StorageType::JSON_FILE;
    config.contextConfig.storagePath = ""; // SessionManager will set this per-session
    config.contextConfig.idleConsolidationSeconds = 60;

    config.skillDirectory = "./my_skills";

    config.modelConfig.baseUrl = "<YOUR_MODEL_BASE_URL>";
    config.modelConfig.apiKey = "<YOUR_MODEL_API_KEY>";
    config.modelConfig.modelName = "<YOUR_MODEL_NAME>";
    config.modelConfig.formatType = ModelFormatType::OPENAI;

    config.modelConfig.extraParams.Set("max_tokens", 4096);
    config.modelConfig.extraParams.Set("temperature", 0.0f);
    config.modelConfig.extraParams.Set("top_p", 0.0f);
    config.modelConfig.extraParams.Set("tool_choice", std::string("auto"));

    config.promptTemplates["react_system"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/REACT_SYSTEM.md"
    };

    config.promptTemplates["agents"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/AGENTS.md"
    };
    config.promptTemplates["soul"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/SOUL.md"
    };
    config.promptTemplates["user"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/USER.md"
    };
    config.promptTemplates["tools_md"] = PromptResource{
        PromptResourceType::FILE_PATH,
        "./examples/jiuwenClaw/templates/TOOLS.md"
    };

    // Default tools for all sessions
    auto& rm = ResourceManager::GetInstance();
    auto allTools = rm.GetAvailableTools();
    config.defaultTools = allTools;

    return config;
}

void RegisterArkCodeModel()
{
    // ArkCode is OpenAI-compatible but has special handling for tool role messages
    // Register custom implementation to handle these differences
    // If fully compatible with OpenAI, no custom Model needed - just set formatType=OPENAI
    auto& rm = ResourceManager::GetInstance();
    rm.RegisterModel("ark_code", [](const ModelConfig& cfg) { return std::make_unique<ArkCodeModel>(cfg); });
}

void RegisterDemoTools()
{
    auto& rm = ResourceManager::GetInstance();
    rm.RegisterTool("notebook_edit", []() { return std::make_unique<NotebookEditTool>(); });
    rm.RegisterTool("cron", []() { return std::make_unique<CronTool>(); });
    rm.RegisterTool("notify", []() { return std::make_unique<NotifyTool>(); });
}

void RunCliMode()
{
    std::cout << "\nEnter '/exit' to quit, '/session <id>' to switch session.\n" << std::flush;

    // Session management for CLI
    std::string currentSession = kDefaultSessionId;

    std::string query;
    while (g_Running) {
        std::cout << "[" << currentSession << "]> " << std::flush;
        if (!std::getline(std::cin, query)) {
            break;
        }

        if (query == "/exit") {
            LOG(INFO) << "User input: " << query;
            g_Running = false;
            break;
        }

        if (query.empty()) {
            continue;
        }

        // Handle /session command to switch between sessions
        if (query.substr(0, 9) == "/session ") {
            currentSession = TrimStr(query.substr(9));
            if (currentSession.empty()) {
                currentSession = kDefaultSessionId;
            }
            // Create session via SessionManager
            GetSessionManager().GetOrCreateSession(currentSession);
            LOG(INFO) << "[CLI] Switched to session: " << currentSession;
            std::cout << "[Info] Switched to session: " << currentSession << "\n";
            continue;
        }

        // Handle /sessions command to list active sessions
        if (query == "/sessions") {
            auto ids = GetSessionManager().GetSessionIds();
            std::cout << "Active sessions (" << ids.size() << "): ";
            for (size_t i = 0; i < ids.size(); ++i) {
                if (i > 0) {
                    std::cout << ", ";
                }
                std::cout << ids[i] << (ids[i] == currentSession ? " (current)" : "");
            }
            std::cout << "\n";
            continue;
        }

        // Handle /reload [agent [<id>] | channels]
        if (query == "/reload" || query.substr(0, 8) == "/reload ") {
            std::string rest = query.length() > 8 ? TrimStr(query.substr(8)) : "";
            if (rest.empty()) {
                std::cout << "[Reload] Reloading agents.json and channels.json...\n";
                ReloadAll();
                std::cout << "[Reload] Done.\n";
            } else if (rest == "channels") {
                std::cout << "[Reload] Reconciling channels...\n";
                ReloadChannels();
                std::cout << "[Reload] Done.\n";
            } else if (rest.substr(0, 5) == "agent") {
                std::string id = rest.length() > 6 ? TrimStr(rest.substr(6)) : "";
                std::cout << "[Reload] Reloading agent '" << (id.empty() ? "<default>" : id) << "'...\n";
                bool ok = ReloadAgent(id);
                std::cout << (ok ? "[Reload] Done.\n" : "[Reload] Failed (see logs).\n");
            } else {
                std::cout << "Usage: /reload | /reload agent [<id>] | /reload channels\n";
            }
            continue;
        }

        // Handle /config show [<id>]
        if (query == "/config show" || query.substr(0, 13) == "/config show ") {
            std::string id = query.length() > 13 ? TrimStr(query.substr(13)) : "";
            if (id.empty()) {
                id = GetSessionManager().GetConfig().id;
            }
            auto cfgOpt = AgentConfigStore::Instance().Get(id);
            if (!cfgOpt) {
                std::cout << "[Config] No agent with id=" << id << "\n";
            } else {
                std::cout << AgentConfigToJson(*cfgOpt).dump(2) << "\n";
            }
            continue;
        }

        std::string utf8Query = LocalToUTF8(query);
        utf8Query = CleanInput(utf8Query);
        utf8Query = FixUTF8(utf8Query);
        utf8Query = TrimStr(utf8Query);
        if (utf8Query.empty()) {
            continue;
        }

        std::cout << "Processing...\n";

        std::string utf8Carry;

        const std::string TAG_STREAM = "[STREAM]";
        const std::string TAG_STATUS = "[STATUS]";
        const std::string TAG_TOOL_CALLS = "[TOOL_CALLS]";
        const std::string TAG_TOOL_RESPONSE = "[TOOL_RESPONSE]";
        const std::string TAG_FINAL = "[FINAL]";

        // Invoke via SessionManager with per-session lock and concurrency gate
        SessionInvokeResult result = GetSessionManager().Invoke(
            currentSession,
            utf8Query,
            [&](const std::string& resp) {
                if (resp.empty()) {
                    return;
                }

                std::string s = resp;
                // 1. Tool calls, content overlaps with streaming, no echo
                if (s.find(TAG_TOOL_CALLS) != std::string::npos) {
                    return;
                }

                // 2. Tool response
                if (s.find(TAG_TOOL_RESPONSE) != std::string::npos) {
                    size_t start_pos = s.find(TAG_TOOL_RESPONSE);
                    if (start_pos != std::string::npos) {
                        start_pos += TAG_TOOL_RESPONSE.length();
                        while (start_pos < s.length() && s[start_pos] == ' ') {
                            ++start_pos;
                        }
                        std::string toolRespText = s.substr(start_pos);
                        std::cout << "\n\n**Tool Response**: \n" << UTF8ToLocal(toolRespText) << std::endl;
                    }
                    return;
                }

                // 3. Streaming output
                if (s.find(TAG_STREAM) != std::string::npos) {
                    size_t start_pos = s.find(TAG_STREAM);
                    if (start_pos != std::string::npos) {
                        start_pos += TAG_STREAM.length();
                        while (start_pos < s.length() && s[start_pos] == ' ') {
                            ++start_pos;
                        }
                        std::string cleanText = s.substr(start_pos);

                        if (!cleanText.empty()) {
                            std::string fixed = FixUTF8Streaming(cleanText, utf8Carry);
                            std::cout << UTF8ToLocal(fixed) << std::flush;
                        }
                    }
                    return;
                }

                // 4. Status info
                if (s.find(TAG_STATUS) != std::string::npos) {
                    size_t start_pos = s.find(TAG_STATUS);
                    if (start_pos != std::string::npos) {
                        start_pos += TAG_STATUS.length();
                        while (start_pos < s.length() && s[start_pos] == ' ') {
                            ++start_pos;
                        }
                        std::string statusText = s.substr(start_pos);
                        std::string formattedStatus = "\n>> " + TrimStr(statusText) + "\n";
                        std::cout << UTF8ToLocal(formattedStatus) << std::flush;
                    }
                    return;
                }

                // 5. [FINAL] tag means done, no special handling
                if (s.find(TAG_FINAL) != std::string::npos) {
                    return;
                }

                // 6. Fallback: plain text without tag
                if (!s.empty()) {
                    std::cout << UTF8ToLocal(s) << std::flush;
                }
            }
        );

        std::cout << "\n";
    }
}

// === Hot-reload helpers ===

// Reload one agent by id (default = current SessionManager config id).
// Returns true on success, false on error (e.g. id not found).
bool ReloadAgent(const std::string& agentId)
{
    auto& store = AgentConfigStore::Instance();
    store.Load(); // Re-read agents.json (merged with defaults)

    std::string id = agentId;
    if (id.empty()) {
        id = GetSessionManager().GetConfig().id;
        if (id.empty()) {
            id = "demo-agent";
        }
    }

    auto cfgOpt = store.Get(id);
    if (!cfgOpt) {
        LOG(ERR) << "[Reload] No agent found with id=" << id;
        return false;
    }

    std::string err;
    if (GetSessionManager().ReloadAgent(*cfgOpt, &err)) {
        LOG(INFO) << "[Reload] Agent '" << id << "' hot-reloaded successfully";
        return true;
    }
    LOG(ERR) << "[Reload] Hot-reload failed for '" << id << "': " << err;
    return false;
}

void ReloadChannels()
{
    auto& mgr = ChannelManager::GetInstance();
    mgr.Load(); // re-read channels.json
    ChannelService::Instance().ReconcileAll();
    LOG(INFO) << "[Reload] Channels reconciled";
}

void ReloadAll()
{
    ReloadAgent("");
    ReloadChannels();
}

void PrintUsage()
{
    std::cout << "Usage: jiuwenClaw [OPTIONS]\n"
              << "\n"
              << "Options:\n"
              << "  --server       Enable all integrations (HTTP REST API + configured channels)\n"
              << "  --port <N>     Set server port (default: 8080)\n"
              << "  --host <IP>    Set server host (default: 127.0.0.1)\n"
              << "  --no-cli       Disable CLI mode (run only as daemon)\n"
              << "  --watch-config Auto-reload agent/channels when files change (polled)\n"
              << "  --help         Show this help message\n"
              << "\n"
              << "Notes:\n"
              << "  Agent overrides are loaded from ./data/agents.json (multi-agent ready);\n"
              << "  if absent, the in-code BuildAgentConfig() default is used.\n"
              << "  Channels (e.g. Feishu) are loaded from ./data/channels.json.\n"
              << "  Use the web UI, the REST API, or edit the files directly.\n"
              << "\n"
              << "Interactive CLI commands (in default mode):\n"
              << "  /exit                  Quit\n"
              << "  /session <id>          Switch to a different session\n"
              << "  /sessions              List active sessions\n"
              << "  /reload                Reload agents.json + channels.json\n"
              << "  /reload agent [<id>]   Reload one agent (default: demo-agent)\n"
              << "  /reload channels       Reconcile channels with channels.json\n"
              << "  /config show [<id>]    Print the effective agent config\n"
              << "\n"
              << "Examples:\n"
              << "  jiuwenClaw                          # CLI only (default)\n"
              << "  jiuwenClaw --server                 # CLI + HTTP server + all configured channels\n"
              << "  jiuwenClaw --server --no-cli        # Daemon mode (HTTP + channels)\n"
              << "  jiuwenClaw --server --watch-config  # Server with auto-reload on file change\n"
              << std::endl;
}

int main(int argc, char* argv[])
{
    std::cout << "jiuwenClaw - Agent powered by jiuwen-lite Agent Framework\n====================\n" << std::flush;

    bool enableServer = false;
    bool enableCli = true;
    bool enableWatch = false;
    std::string serverHost = "127.0.0.1";
    int serverPort = 8080;

    // Parse command line arguments
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--server") {
            enableServer = true;
        } else if (arg == "--no-cli") {
            enableCli = false;
        } else if (arg == "--watch-config") {
            enableWatch = true;
        } else if (arg == "--port" && i + 1 < argc) {
            serverPort = std::stoi(argv[++i]);
        } else if (arg == "--host" && i + 1 < argc) {
            serverHost = argv[++i];
        } else if (arg == "--help") {
            PrintUsage();
            return 0;
        }
    }

    // Register custom ArkCode model provider
    RegisterArkCodeModel();
    std::cout << "[Boot] ArkCode model provider registered\n" << std::flush;

    // Register additional tools
    RegisterDemoTools();
    std::cout << "[Boot] Demo tools registered\n" << std::flush;

    // Build the hard-coded default (kept for backward compatibility)
    AgentConfig defaultConfig = BuildAgentConfig();
    std::cout << "[Boot] Default AgentConfig built (id=" << defaultConfig.id << ")\n" << std::flush;

    // Register the default in the config store, then load + merge agents.json.
    auto& cfgStore = AgentConfigStore::Instance();
    cfgStore.SetPersistPath("./data/agents.json");
    cfgStore.RegisterDefault(defaultConfig);
    auto effective = cfgStore.Load();

    // Use the merged config for the primary agent id.
    AgentConfig config = defaultConfig;
    auto it = effective.find(defaultConfig.id);
    if (it != effective.end()) {
        config = it->second;
        std::cout << "[Boot] Effective AgentConfig (default + agents.json overrides) ready\n"
                  << std::flush;
    } else {
        std::cout << "[Boot] No override in agents.json; using code default\n" << std::flush;
    }

    InitSessionManager(config);
    std::cout << "[Boot] SessionManager initialized\n" << std::flush;

    // Load MCP servers from the application-layer registry (mcp_servers.json).
    // The framework itself only knows how to register/connect McpServerConfig
    // objects; it does not care where those configs come from. Other apps
    // can supply them via hard-coded values or their own config loader.
    {
        auto& mcpMgr = McpServerManager::GetInstance();
        mcpMgr.SetPersistPath("./data/mcp_servers.json");
        mcpMgr.Load(); // tolerate missing file (empty pool is a valid state)
        auto configs = mcpMgr.ToFrameworkConfigs();
        if (!configs.empty()) {
            ResourceManager::GetInstance().LoadMCPServers(configs);
            // Sync MCP-discovered tools into the Agent so they appear in the prompt
            if (auto agent = GetSessionManager().GetAgent()) {
                int n = agent->SyncMcpTools();
                std::cout << "[Boot] Synced " << n << " MCP tool(s) to Agent\n" << std::flush;
            }
            std::cout << "[Boot] Loaded " << configs.size()
                      << " MCP server(s) from mcp_servers.json\n" << std::flush;
        } else {
            std::cout << "[Boot] No MCP servers configured (edit ./data/mcp_servers.json or use the web UI to add)\n"
                      << std::flush;
        }
    }

    // Initialize heartbeat and cron using reserved sessions
    HeartbeatManager heartbeat(
        "./data/HEARTBEAT.md",
        config.modelConfig,
        300
    );
    std::cout << "[Boot] HeartbeatManager constructed\n" << std::flush;

    CronWatcher cronWatcher("./data", config.modelConfig, 60);
    std::cout << "[Boot] CronWatcher constructed\n" << std::flush;

    // Start HTTP server if enabled
    if (enableServer) {
        g_HttpServer = std::make_unique<HttpServer>();
        HttpServerConfig httpConfig;
        httpConfig.host = serverHost;
        httpConfig.port = serverPort;
        httpConfig.staticDir = "./examples/jiuwenClaw/web";
        g_HttpServer->Start(httpConfig);
        std::cout << "[Boot] HTTP server started at " << serverHost << ":" << serverPort << "\n" << std::flush;

        // Load channels from disk and start each enabled channel via ChannelService
        auto& channelMgr = ChannelManager::GetInstance();
        channelMgr.SetPersistPath("./data/channels.json");
        channelMgr.Load();
        ChannelService::Instance().StartAll();
        auto active = ChannelService::Instance().ActiveIds();
        if (active.empty()) {
            std::cout << "[Boot] No channels active (edit ./data/channels.json or use the web UI to add)\n"
                      << std::flush;
        } else {
            std::cout << "[Boot] Active channels: " << active.size() << "\n" << std::flush;
        }
    }

    // Optional config-file watcher: auto-reload on disk change
    if (enableWatch) {
        g_ConfigWatcher = std::make_unique<ConfigWatcher>();
        g_ConfigWatcher->Watch("./data/agents.json", [](const std::string& p) {
            (void)p;
            LOG(INFO) << "[Watch] agents.json changed -> hot-reload";
            ReloadAgent("");
        });
        g_ConfigWatcher->Watch("./data/channels.json", [](const std::string& p) {
            (void)p;
            LOG(INFO) << "[Watch] channels.json changed -> reconcile";
            ReloadChannels();
        });
        g_ConfigWatcher->Watch("./data/mcp_servers.json", [](const std::string& p) {
            (void)p;
            LOG(INFO) << "[Watch] mcp_servers.json changed -> reload MCP pool";
            auto& mcpMgr = McpServerManager::GetInstance();
            mcpMgr.Load();
            ResourceManager::GetInstance().LoadMCPServers(mcpMgr.ToFrameworkConfigs());
            // Sync discovered tools to live Agent
            if (auto agent = GetSessionManager().GetAgent()) {
                agent->SyncMcpTools();
            }
        });
        g_ConfigWatcher->Start(3);
        std::cout << "[Boot] Config watcher enabled (poll every 3s)\n" << std::flush;
    }

    std::signal(SIGINT, SignalHandler);
    std::signal(SIGTERM, SignalHandler);

    if (enableCli) {
        RunCliMode();
    } else {
        // Daemon mode: wait for signal
        std::cout << "[Boot] Running in daemon mode. Press Ctrl+C to stop...\n" << std::flush;
        while (g_Running) {
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
    }

    // Cleanup
    std::cout << "\n[Shutdown] Stopping services...\n" << std::flush;

    if (g_ConfigWatcher) {
        g_ConfigWatcher->Stop();
        g_ConfigWatcher.reset();
    }

    ChannelService::Instance().StopAll();

    if (g_HttpServer) {
        g_HttpServer->Stop();
        g_HttpServer.reset();
    }

    std::cout << "[Shutdown] Goodbye.\n" << std::flush;

    return 0;
}
